name: Production deployment

on:
  push:
    branches:
      - main

permissions:
  contents: read

env:
  NEXT_TELEMETRY_DISABLED: 1
  VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}
  VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
  VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN }}
  ALGOLIA_APP_ID: ${{secrets.ALGOLIA_APP_ID}}
  ALGOLIA_INDEX_NAME: ${{secrets.ALGOLIA_INDEX_NAME}}
  ALGOLIA_SEARCH_KEY: ${{secrets.ALGOLIA_SEARCH_KEY}}

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  deploy-prod:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # 6.0.2
        with:
          ref: "main"
      - name: Setup Node.js
        uses: actions/setup-node@53b83947a5a98c8d113130e565377fae1a50d02f # 6.3.0
        with:
          node-version: 22
      - name: Enable Corepack
        run: |
          corepack enable
          corepack prepare yarn@4.12.0 --activate
      - name: Install Vercel CLI
        run: npm install --global vercel@canary
      - name: Pull Vercel Environment Information
        run: vercel pull --yes --environment=production --token=${{ secrets.VERCEL_TOKEN }} --scope=${{ secrets.VERCEL_ORG_ID }}
      - name: Build Project Artifacts
        run: vercel build --prod --token=${{ secrets.VERCEL_TOKEN }} --scope=${{ secrets.VERCEL_ORG_ID }}
      - name: Deploy Project Artifacts to Prod Vercel
        run: |
          DEPLOYMENT_URL=$(vercel deploy --prebuilt --prod --archive=tgz --token=${{ secrets.VERCEL_TOKEN }} --scope=${{ secrets.VERCEL_ORG_ID }})
          echo "Production Deployment URL: $DEPLOYMENT_URL"
          vercel alias set $DEPLOYMENT_URL midnight-wiki.vercel.app --token=${{ secrets.VERCEL_TOKEN }} --scope=${{ secrets.VERCEL_ORG_ID }}