name: Vale Docs Lint

on:
  pull_request:
    paths:
      - "docs/**"
      - "**.mdx"
      - "sdks/**"

permissions:
  contents: read
  pull-requests: write

      
jobs:
  vale:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2

      - uses: actions/setup-node@53b83947a5a98c8d113130e565377fae1a50d02f # 6.3.0
        with:
          node-version: 22
    
      - run: npm install -g mdx2vast

      - name: Run Vale
        uses: errata-ai/vale-action@d89dee975228ae261d22c15adcd03578634d429c # v2.1.1
        with:
          reporter: github-pr-review
          filter_mode: added
          files: '["docs", "sdks"]'
          fail_on_error: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}